local f = io.open('kazem.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 kazem.sh')
os.execute('killall -9 tg')
os.execute('rm -rf kazem.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('kazem.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 kazem.sh')
os.execute('screen ./kazem.sh')
